adding working files on HW
yevheniia-petrychenko/nodejs-homework-Rest-API pull request #2
Opened 2021-05-16 19:37 UTC by yevheniia-petrychenko

2021-05-17 20:21 UTC, SergeiKBB requested changes

2021-05-17 20:21 UTC, SergeiKBB commented on .env
> +URI_DB=mongodb+srv://Yevheniia:123654@hwonnode.jacxx.mongodb.net/contacts?retryWrites=true&w=majority
этот файл должен быть добавлен в гитигнореф

2021-05-18 09:30 UTC, yevheniia-petrychenko reviewed
.env is added to gitignire

2021-05-19 20:43 UTC, SergeiKBB approved these changes

2021-05-21 13:38 UTC, merged